#!/bin/bash
if [ -z "$1" ]
then
    cachedir='/var/www/book/cache/anon';
    echo "set cache directory to $cachedir"
    mkdir $cachedir
else
    cachedir=$1;
fi

. ./changedir.sh $cachedir

export CLASSPATH=/var/www/tmp/rhino1_7R1/js.jar:$CLASSPATH
/usr/bin/java org.mozilla.javascript.tools.shell.Main javascript
pdflatex -interaction nonstopmode book.tex > pdflatex.log
rm book.aux book.log
cat pdflatex.log
